# Generated by Django 4.0.5 on 2022-06-07 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('guests', models.IntegerField(default=0)),
            ],
        ),
    ]
